### ISSUE TITLE
下一步的时候怎么提交表单

### ISSUE THREAD

**Issue by kyxiao** [HsuanXyz/ionic-stepper#1]
大神你好，这个插件挺好但是我在使用中有点问题，我在ionic3里是这样写的，想下一步的时候提交表单，但是直接跳下一步了，并没有执行type="submit"动作
<button type="submit" ion-button myStepperNext [disabled]="!compData.bailMethod">保存并继续</button>，求一个解决办法

**Comment by HsuanXyz** [comment]
抱歉现在才回复(也许你已经解决了)，我已经更新了配合 `form` 使用的 demo。
![form](https://user-images.githubusercontent.com/22736418/37810297-341a9912-2e8e-11e8-9637-0b3a0da45dfe.gif)
